# Generated by Django 2.1.7 on 2019-03-03 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='published_at',
            new_name='published_date',
        ),
        migrations.RemoveField(
            model_name='book',
            name='created_date',
        ),
    ]
