# Generated by Django 2.1.7 on 2019-03-12 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CRUDLog',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('logger_name', models.CharField(max_length=100)),
                ('msg', models.CharField(max_length=255)),
                ('trace', models.CharField(max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
